# Brew
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'heroku/brew'

brew 'ack'
brew 'asdf'
brew 'autojump'
brew 'bat'
brew 'curl'
brew 'diff-so-fancy'
brew 'direnv'
brew 'exa'
brew 'fzf'
brew 'git'
brew 'gh'
brew 'heroku'
brew 'nginx'
brew 'prettyping'
brew 'sqlite'
brew 'tmate'
brew 'TomAnthony/brews/itermocil'
brew 'wget'

brew 'zsh'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'

brew 'autoconf'
brew 'cmake'
brew 'coreutils'
brew 'ffmpeg'
brew 'fontconfig'
brew 'freetype'
brew 'gcc'
brew 'gettext'
brew 'glib'
brew 'gpg'
brew 'imagemagick'
brew 'jpeg'
brew 'libffi'
brew 'libiconv'
brew 'libpng'
brew 'libssh'
brew 'libtool'
brew 'libxml2'
brew 'libxslt'
brew 'libyaml'
brew 'openjpeg'
brew 'openssl'
brew 'pkg-config'
brew 'readline'
brew 'unzip'
brew 'webkit2png'
brew 'webp'
brew 'wxmac'
brew 'yarn'
brew 'zlib'

# MAS
brew 'mas'

mas 'Clocker', id: 1056643111
mas 'TranslateTab', id: 458887729

# CASK
tap 'homebrew/cask'
tap 'homebrew/cask-versions'
brew 'brew-cask-completion'

cask 'alfred3'
cask 'authy'
cask 'dash'
cask 'discord'
cask 'docker'
cask 'dropshare'
cask 'gitify'
cask 'google-backup-and-sync'
cask 'google-chrome-beta'
cask 'grammarly'
cask 'imageoptim'
cask 'insomnia'
cask 'iterm2'
cask 'itsycal'
cask 'monodraw'
cask 'muzzle'
cask 'postgres'
cask 'psequel'
cask 'sequel-pro'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'the-unarchiver'
cask 'typora'
cask 'visual-studio-code'
