#!/usr/bin/env bash

# Load utils
source ${DOTFILES_INSTALLER}/utils

###############################################################################
# Git
###############################################################################

print_in_yellow 'Starting Git Configuration...\n'

# Create symbolic link to default files
ln -sf ${DOTFILES_FILES_CONFIGS}/gitconfig ~/.gitconfig
ln -sf ${DOTFILES_FILES_CONFIGS}/gitignore ~/.gitignore
ln -sf ${DOTFILES_FILES_CONFIGS}/gitmessage ~/.gitmessage

print_success 'Git Configuration done!\n'
