#!/usr/bin/env bash

# Load utils
source ${DOTFILES_INSTALLER}/utils

###############################################################################
# Ruby
###############################################################################

print_in_yellow 'Ruby configurations...\n'

# Create symbolic link to default files
ln -sf ${DOTFILES_FILES_CONFIGS}/gemrc ~/.gemrc
ln -sf ${DOTFILES_FILES_CONFIGS}/irbrc ~/.irbrc
ln -sf ${DOTFILES_FILES_CONFIGS}/pryrc ~/.pryrc
ln -sf ${DOTFILES_FILES_CONFIGS}/railsrc ~/.railsrc
