#!/usr/bin/env bash

# Load utils
source ${DOTFILES_INSTALLER}/utils

###############################################################################
# Shell
###############################################################################

print_in_yellow 'Shell configurations...\n'

# Copy binaries to ~/.bin
ln -sf ${DOTFILES_DIR}/bin ~/.bin

# Create symbolic links
ln -sf ${DOTFILES_FILES_CONFIGS}/zshrc ~/.zshrc
ln -sf ${DOTFILES_FILES_CONFIGS}/inputrc ~/.inputrc
ln -sf ${DOTFILES_FILES_CONFIGS}/agignore ~/.agignore
ln -sf ${DOTFILES_FILES_CONFIGS}/ackrc ~/.ackrc

# Install zsh themes
ln -sf ${DOTFILES_THEMES_DIR}/materialshell.zsh-theme ~/.oh-my-zsh/themes/materialshell.zsh-theme
ln -sf ${DOTFILES_THEMES_DIR}/ricardoruwer.zsh-theme ~/.oh-my-zsh/themes/ricardoruwer.zsh-theme

# Install shell extesions for fzf
/usr/local/opt/fzf/install

# Install Oh-My-Zsh
if [ -n "`$SHELL -c 'echo $ZSH_VERSION'`" ]; then
  print_success 'Oh-My-Zsh already installed.\n'
else
  ask_for_confirmation 'Would you like to install Oh-My-Zsh?'

  if answer_is_yes; then
    print_success 'Starting installing Oh-My-Zsh.\n'
    cd ~
    curl -Ls https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh &> /dev/null
  else
    print_in_yellow 'Skipping Oh-My-Zsh installation.\n'
  fi
fi

# Change my shell to zsh
chsh -s /bin/zsh

print_success 'Shell configured.\n'
