#!/usr/bin/env bash

# Load utils
source ${DOTFILES_INSTALLER}/utils

###############################################################################
# Shell
###############################################################################

print_in_yellow 'Sublime Text configurations...\n'

st3_path="/Users/ricardoruwer/Library/Application Support/Sublime Text 3/Packages"

mv "$st3_path/User" "$st3_path/User.bkp"
ln -sf ${DOTFILES_FILES}/sublime-text "$st3_path/User"
