# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load @ ~/.oh-my-zsh/themes/ or ~/.oh-my-zsh/custom/themes/
# ZSH_THEME=''

# Tab title
DISABLE_AUTO_TITLE="true"

# Spaceship configs
SPACESHIP_PROMPT_ORDER=(char user host dir git jobs exit_code)

SPACESHIP_DIR_PREFIX=""

SPACESHIP_GIT_PREFIX="("
SPACESHIP_GIT_SUFFIX=") "
SPACESHIP_GIT_BRANCH_PREFIX=""
SPACESHIP_GIT_STATUS_PREFIX=""
SPACESHIP_GIT_STATUS_SUFFIX=""

# ZSH Plugins
plugins=(autojump gitfast docker mix heroku)

# Stamp shown in the history command output.
HIST_STAMPS='dd/mm/yyyy'

# User configuration
source $ZSH/oh-my-zsh.sh

# Dotfiles (aliases, functions, exports, etc.)
for file in ~/.dotfiles/shell/*; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# Dotfiles autocomplete
if [ -f ~/.dotfiles/autocomplete.sh ]; then
  source ~/.dotfiles/autocomplete.sh
fi;
if [ -f ~/.dotfiles/privy/autocomplete.sh ]; then
  source ~/.dotfiles/privy/autocomplete.sh
fi;

# Functions to be executed after every command
chpwd() { onload_function }
precmd() { onload_function }
onload_function

# Fuzzy finder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# ASDF
. /usr/local/opt/asdf/asdf.sh
. /usr/local/opt/asdf/etc/bash_completion.d/asdf.bash

# Itermocil
compctl -g '~/.itermocil/*(:t:r)' itermocil

# Heroku autocomplete setup
HEROKU_AC_ZSH_SETUP_PATH=$HOME/Library/Caches/heroku/autocomplete/zsh_setup && test -f $HEROKU_AC_ZSH_SETUP_PATH && source $HEROKU_AC_ZSH_SETUP_PATH;

# zsh-completions
FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
autoload -Uz compinit
compinit

# zsh-syntax-highlighting
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# iTerm2 shell integrations
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Set Spaceship ZSH as a prompt
autoload -U promptinit; promptinit
prompt spaceship

eval "$(direnv hook zsh)"
