# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Tab title
DISABLE_AUTO_TITLE="true"

# Spaceship configs
source $(brew --prefix)/opt/spaceship/spaceship.zsh

SPACESHIP_PROMPT_ORDER=(char user host dir git jobs exit_code async)
SPACESHIP_DIR_PREFIX=""
SPACESHIP_GIT_PREFIX="("
SPACESHIP_GIT_SUFFIX=") "
SPACESHIP_GIT_BRANCH_PREFIX=""
SPACESHIP_GIT_STATUS_PREFIX=""
SPACESHIP_GIT_STATUS_SUFFIX=""
SPACESHIP_ASYNC_SYMBOL=""

# ZSH Plugins
plugins=(asdf autojump gitfast docker mix heroku iterm-tab-color)

# Stamp shown in the history command output.
HIST_STAMPS='dd/mm/yyyy'

# User configuration
source $ZSH/oh-my-zsh.sh

# Dotfiles (aliases, functions, exports, etc.)
for file in ~/.dotfiles/shell/*; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# Dotfiles autocomplete
if [ -f ~/.dotfiles/autocomplete.sh ]; then
  source ~/.dotfiles/autocomplete.sh
fi;
if [ -f ~/.dotfiles/privy/autocomplete.sh ]; then
  source ~/.dotfiles/privy/autocomplete.sh
fi;

# Functions to be executed after every command
onload_function() {
  title "%c"

  if [ -d .git ]; then
    branch=$(git symbolic-ref --quiet --short HEAD)
  else
    unset branch
  fi;
}

chpwd() { onload_function }
precmd() { onload_function }
onload_function

# Fuzzy finder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Itermocil
compctl -g '~/.itermocil/*(:t:r)' itermocil

# Heroku autocomplete setup
HEROKU_AC_ZSH_SETUP_PATH=$HOME/Library/Caches/heroku/autocomplete/zsh_setup && test -f $HEROKU_AC_ZSH_SETUP_PATH && source $HEROKU_AC_ZSH_SETUP_PATH;

# zsh-completions
FPATH="$(brew --prefix)/share/zsh/site-functions:$FPATH"
autoload -Uz compinit
compinit

# zsh-syntax-highlighting
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# iTerm2 shell integrations
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

eval "$(direnv hook zsh)"
